title Arch Linux
linux /vmlinuz-linux-zen
initrd /intel-ucode.img
initrd /initramfs-linux-zen.img
options root=/dev/nvme0n1p2 zswap.enabled=0 mitigations=off i915.enable_fbc=1 intel_pstate=passive rw rootfstype=ext4 pcie_aspm.policy=performance thunderbolt.host_reset=0 pci=hpbussize=0x33,hpmemsize=256M,hpmmiosize=256M,hpmmioprefsize=32G,realloc,nocrs
